### ISSUE TITLE
Mechanical design

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/BATDATUNIT01#1]
Modul by měl být konstrukčně podobný tomuto modulu: https://github.com/ust-modules/UST5BATT18650V01

To znamená pro připojení článků 18650 využívat pouzdro, ve kterém je možné jednotlivé články vyměnit. 

Zásadní rozdíl je v tom, že tento modul má testovat možnost konstrukce vyjímatelného bateriového pouzdra, tudíž by jeho mechanická realizace měla být přibližně takováto: 

![image](https://github.com/mlab-modules/LIONXCELL01/assets/1194177/3f739335-05a2-46f5-a404-5d3408a1ea99)

Vodící lišty budou vytištěné vnější stranou na podložku. Tím by měl být tisk hladký a PCB by jezdilo po vrstvách. Zároveň by se zde měla minimálně projevovat křivost tiskáren. 
Vodící lišta by se k MLAB desce přišroubovala standardně pomocí šroubů. Na čele vodící lišty by byly M3 otvory se závitovými vložkami, do kterých by se bateriový modul zajistil pomocí šroubů s velkou hlavou. 

Na zadní straně lišty by byl vložený PCB s protikusem konektoru. Tento PCB by měl stejný rozměr (šířku) jako PCB bateriového modulu. Modul by byl zajištěn sešroubováním s vodící lištou. Zřejmě z vrchní strany. 

Adaptér by obsahoval hřebínky pro univerzální použití (I2C, napájení, atd.) Mechanicky by to bylo spojené přes vodící lištu.

**Comment by roman-dvorak** [comment]
Pro spojení s měřící částí v detektorech není úplně žádoucí, aby tam byly hřebínky. Pro tento účel existují dvě navrhované řešení. Obě řešení předpokládaji, že měřící PCB bude umístěno paralelně pod akumulátorovým PCB. Tak, aby to bylo efektivní z hlediska využití prostoru. 

Jedno řešení předpokládá spojení pomocí rigid-flex PCB, kdy rigidflex PCB bude tvořit ohyb o 180 stupňů. Druhé řešení počítá sletování obou desek pomocí dlouhých "hřebínků". Je to znázorněno na tomto nákresu. 


![Snímek obrazovky z 2023-09-10 02-32-21](https://github.com/mlab-modules/LIONXCELL01/assets/5196729/fa9f4239-8118-49e3-96e5-4ef180e6f008)


Bylo by užitečné umět implementovat oba přístupy.

**Comment by kaklik** [comment]
Aktuální řešení je pro účely MLABu dostatečné.
