### ISSUE TITLE
Switch power supply Pull-down resistors value

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/BATDATUNIT01#5]
Aktuálně jsou v zapojení pull-down rezistory 1k, které mají zabránit sepnutí měničů v případě, že MCU měniče neovládá.

![image](https://github.com/mlab-modules/BATDATUNIT01/assets/1194177/265fbb95-1057-41f2-b824-a4cb9e6bce41)

Hodnota rezistorů by se měla buď zvětšit alespoň na 100k, nebo rezistory úplně odstranit.

**Comment by roman-dvorak** [comment]
Označme je jako DNF, neodstranoval bych je.

**Comment by roman-dvorak** [comment]
![obrazek](https://github.com/mlab-modules/BATDATUNIT01/assets/5196729/f16092a4-6095-4442-9aad-87517a1aabb4)
